import {
  EmailActionItem,
  EmailTemplateContent,
  EmailTemplateKey,
  EmailTemplateRegistry,
  EmployeeManagerRule,
  SectionMailboxRule,
} from '../types/taa';

export const EMAIL_TEMPLATE_KEYS: EmailTemplateKey[] = [
  'late_login_absence',
  'early_logout_absence',
  'late_logout_absence',
  'no_login_ns_nc',
  'single_punch_absence',
  'cover_not_attended',
  'generic',
  'ops_digest',
  'improper_login_logout',
];

export const EMAIL_TEMPLATE_LABELS: Record<EmailTemplateKey, string> = {
  late_login_absence: 'Late-login absence',
  early_logout_absence: 'Early-logout absence',
  late_logout_absence: 'Late-logout absence',
  no_login_ns_nc: 'No-login NS/NC',
  single_punch_absence: 'Single-punch absence',
  cover_not_attended: 'Cover not attended',
  generic: 'Generic fallback',
  ops_digest: 'OPS Section digest (pooled)',
  improper_login_logout: 'Improper login/logout (unseen-punch flagged rows)',
};

export const EMAIL_TEMPLATE_PLACEHOLDERS = [
  'name',
  'emp_id',
  'nominate_date',
  // The full internal rule trace, e.g.
  //   "Late Logout (OPS): 43m past the release-adjusted end 17:00
  //    (rostered end 16:45) -> Mark Absent"
  // Useful in an OPS digest, wrong in a message an employee reads — prefer
  // {{finding}} in staff-facing templates.
  'category',
  // Short human label for the same finding, e.g. "Late Logout". Derived by
  // shortenFindingLabel from category.
  'finding',
  'taa_action',
  'variance_minutes',
  'role_tier',
  'communication_rule',
  'resolved_username',
  'login_id',
  'section',
] as const;

// ops_digest is a synthesized whole-group email (see poolEmailOpsActionsBySection
// below), not a single case — its placeholders describe the pooled group, not
// one employee, so the per-case list above does not apply to it.
export const OPS_DIGEST_PLACEHOLDERS = ['section', 'count', 'nominate_date', 'case_table'] as const;

// generic is the ad-hoc/no-action-required fallback (reconciliationEngine.ts
// builds an EmailActionItem for every row now, not just ones a policy rule
// flagged) — its {{finding}}/{{taa_action}} are legitimately blank for those
// rows, so it carries its own extra case-detail placeholders (sourced via
// `extras`, not EmailActionItem fields) so an agent drafting an ad-hoc notice
// still sees everything TAA computed for that row.
export const GENERIC_CASE_DETAIL_PLACEHOLDERS = [
  ...EMAIL_TEMPLATE_PLACEHOLDERS,
  'sch_hours',
  'effective_start',
  'effective_end',
  'cms_in',
  'cms_out',
  'late_min',
  'early_min',
  'verdict',
  'result_category',
  'actions_fired',
] as const;

export const EMAIL_TEMPLATE_PLACEHOLDERS_BY_KEY: Record<EmailTemplateKey, readonly string[]> =
  EMAIL_TEMPLATE_KEYS.reduce((acc, key) => {
    acc[key] = key === 'ops_digest' ? OPS_DIGEST_PLACEHOLDERS
      : key === 'generic' ? GENERIC_CASE_DETAIL_PLACEHOLDERS
      : EMAIL_TEMPLATE_PLACEHOLDERS;
    return acc;
  }, {} as Record<EmailTemplateKey, readonly string[]>);

// PROPOSED WORDING — 2026-09-07, pending user sign-off.
// Only the subject prefix, the opening/intro line, and the closing/disclaimer
// line below are new proposed text (doc/TAA_KNOWLEDGE_BASE.md item 9 /
// doc/PRD.md §8 item 12 mark these as deferred). The structural field block
// (Finding/Action taken/variance/login/section lines and each template's own
// informational note) is unchanged — that part was already confirmed fine.
// Do NOT treat this wording as final; it is a draft awaiting explicit
// approval or edits from the business owner.
export const DEFAULT_EMAIL_TEMPLATES: EmailTemplateRegistry = {
  late_login_absence: {
    subject: 'TAA Attendance Review Notice: Late login absence - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'Variance charged: {{variance_minutes}} minute(s)',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  early_logout_absence: {
    subject: 'TAA Attendance Review Notice: Early logout absence - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'Early logout variance charged: {{variance_minutes}} minute(s)',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  late_logout_absence: {
    subject: 'TAA Attendance Review Notice: Late logout absence - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'Late logout variance charged: {{variance_minutes}} minute(s)',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  no_login_ns_nc: {
    subject: 'TAA Attendance Review Notice: No login NS/NC - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'No usable CMS login/logout punches were found for this employee-day in the reconciled window.',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  single_punch_absence: {
    subject: 'TAA Attendance Review Notice: Incomplete punch pair - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'Only an incomplete punch pair was found for this employee-day after reconciliation.',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  cover_not_attended: {
    subject: 'TAA Attendance Review Notice: Cover not attended - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'Variance charged: {{variance_minutes}} minute(s)',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'A scheduled cover segment was not fully attended in the reconciled CMS window.',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  generic: {
    subject: 'TAA Attendance Review Notice: {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: {{finding}}',
      'Action taken: {{taa_action}}',
      'Variance charged: {{variance_minutes}} minute(s)',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'Case details:',
      'Verdict: {{verdict}} ({{result_category}})',
      'Scheduled hours: {{sch_hours}}',
      'Effective shift window: {{effective_start}} - {{effective_end}}',
      'CMS in / out: {{cms_in}} / {{cms_out}}',
      'Late minutes: {{late_min}} | Early minutes: {{early_min}}',
      'All actions fired this row: {{actions_fired}}',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  ops_digest: {
    subject: 'TAA Attendance Review Notice — OPS Digest: {{section}} - {{count}} case(s) - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) OPS digest for the {{section}} section on {{nominate_date}}, covering {{count}} case(s) below. Please review each entry.',
      '',
      '{{case_table}}',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
  // Deliberately neutral — used only for unseen-punch REASON/OUTCOME-flagged rows
  // (unseenPunchAudit.ts), where a punch outside the search window means the engine's own
  // specific reason (Early/Late Logout, Late Login…) may be wrong. No minutes and no
  // direction (early/late) are named here, on purpose, so the notice never states a
  // possibly-wrong specific finding.
  improper_login_logout: {
    subject: 'TAA Attendance Review Notice: Improper login/logout under review - {{name}} - {{nominate_date}}',
    body: [
      'Hello,',
      '',
      'This is an automated Time & Attendance (TAA) review notice regarding {{name}} (PF {{emp_id}}) for {{nominate_date}}. Please review the details below.',
      '',
      'Finding: Improper login/logout — under review',
      'Action taken: {{taa_action}}',
      'CMS Login ID: {{login_id}}',
      'Section: {{section}}',
      '',
      'A CMS punch was found outside the standard search window for this employee-day, so the specific reason is still under review. This notice intentionally does not state a specific finding until that review is complete.',
      '',
      'This message is an automatically generated DRAFT only — no email has been sent. Please verify all details against the official Cognos discrepancy report before editing or sending. Generated by the TAA Time & Attendance reconciliation tool.',
    ].join('\n'),
  },
};

export function normalizeEmailTemplates(raw: unknown): EmailTemplateRegistry {
  const candidate = raw && typeof raw === 'object' ? raw as Partial<Record<EmailTemplateKey, Partial<EmailTemplateContent>>> : {};
  return EMAIL_TEMPLATE_KEYS.reduce((acc, key) => {
    const supplied = candidate[key];
    acc[key] = {
      subject: typeof supplied?.subject === 'string' ? supplied.subject : DEFAULT_EMAIL_TEMPLATES[key].subject,
      body: typeof supplied?.body === 'string' ? supplied.body : DEFAULT_EMAIL_TEMPLATES[key].body,
    };
    return acc;
  }, {} as EmailTemplateRegistry);
}

// `category` carries the full rule trace the engine built at the firing site —
// tier, measured minutes, the effective vs rostered window, and the action.
// That is exactly what an OPS reviewer wants and exactly what an employee
// should not be handed. This reduces it to the leading rule name ("Late
// Logout", "Cover Not Attended"), dropping the "(TIER): ..." trace and any
// "-> action" tail. Anything unrecognisable is passed through unchanged rather
// than truncated into nonsense.
export function shortenFindingLabel(category: string): string {
  const raw = (category || '').trim();
  if (!raw) return '';
  const beforeTier = raw.split(' (')[0];
  const beforeArrow = beforeTier.split('->')[0];
  const beforeColon = beforeArrow.split(':')[0];
  const short = beforeColon.trim();
  return short.length > 0 ? short : raw;
}

function placeholderValues(action: EmailActionItem): Record<string, string> {
  return {
    name: action.name || '',
    emp_id: action.emp_id || '',
    nominate_date: action.nominate_date || '',
    category: action.category || '',
    finding: shortenFindingLabel(action.category || ''),
    taa_action: action.taa_action || '',
    variance_minutes: String(action.variance_minutes ?? ''),
    role_tier: action.role_tier || '',
    communication_rule: action.communication_rule || '',
    resolved_username: action.resolved_username || '',
    login_id: action.login_id || '',
    section: action.section || '',
  };
}

export function renderTemplateText(
  templateText: string,
  action: EmailActionItem,
  extras?: Record<string, string>,
): { text: string; warnings: string[] } {
  const values = { ...placeholderValues(action), ...(extras || {}) };
  const warnings: string[] = [];
  const text = templateText.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (match, key: string) => {
    if (Object.prototype.hasOwnProperty.call(values, key)) {
      return values[key];
    }
    warnings.push(`Unresolved template placeholder: ${match}`);
    return match;
  });
  return { text, warnings: Array.from(new Set(warnings)) };
}

// Returns template_warnings as REQUIRED, not optional: this function always
// sets it (empty array when everything resolved). EmailActionItem keeps it
// optional because a raw, un-templated action legitimately has no warnings
// field yet — but once this has run, callers can rely on it without a guard.
export function applyEmailTemplate(
  action: EmailActionItem,
  templates: EmailTemplateRegistry,
  extras?: Record<string, string>,
): EmailActionItem & { template_warnings: string[] } {
  const selected = templates[action.template_key] || templates.generic || DEFAULT_EMAIL_TEMPLATES.generic;
  const subject = renderTemplateText(selected.subject, action, extras);
  const body = renderTemplateText(selected.body, action, extras);
  return {
    ...action,
    subject: subject.text,
    body: body.text,
    template_warnings: [...subject.warnings, ...body.warnings],
  };
}

// ---------------------------------------------------------------------------
// Recipient resolution (§4.7) — moved into the browser now that there is no
// Outlook/Exchange companion in the loop to resolve a bare alias against the
// GAL. These are payroll-safety rules, not formatting: getting the order
// wrong can address a disciplinary notice to the wrong employee.
// ---------------------------------------------------------------------------

// True when stripping `value`'s local part is safe because its domain is one
// this organisation controls — mirrors the retired VBA companion's
// TAA_IsResolvableEmailAdr. A domain ending in "." is treated as truncated
// (14 real rows look like "aalali@thecontactcentre.") and prefix-matched
// against the allow-list; anything else foreign (a personal Hotmail/Gmail
// domain, say) is never trusted — its local part can belong to a completely
// different person than the one this row is about.
export function isCorporateEmailDomain(value: string, corporateDomains: string[]): boolean {
  const trimmed = (value || '').trim();
  if (!trimmed) return false;
  const atPos = trimmed.indexOf('@');
  if (atPos === -1) return true; // no domain at all (e.g. a Lotus Notes path) — nothing to distrust
  let domain = trimmed.slice(atPos + 1).toLowerCase();
  let wasTruncated = false;
  while (domain.length > 0 && domain.endsWith('.')) {
    domain = domain.slice(0, -1);
    wasTruncated = true;
  }
  if (!domain) return false;
  return corporateDomains.some(candidate => {
    const c = candidate.trim().toLowerCase();
    if (!c) return false;
    if (c === domain) return true;
    return wasTruncated && c.startsWith(domain);
  });
}

export interface ResolvedRecipient {
  to: string;
  usedNameFallback: boolean;
}

// The three rules, in strict priority order — the username is the base and
// wins whenever it exists; a name is a last resort, never a first choice:
//   1. A username (EMP_EXTRA_2) exists -> "<username>@<corporate domain>".
//      Always. Never fall back to a name while a username is available.
//   2. No username, but EMP_EMAIL_ADR sits on a corporate domain -> use that
//      address as-is (it is already a real address).
//   3. Neither -> the full staff name (Cognos NAME), so Outlook's Check Names
//      forces a human to confirm who this actually is.
// Never strip a username out of a personal-domain address (al_wafa@hotmail.com
// is not a username — the real alias for that person may be entirely
// different) — that resolves silently onto whoever else owns that alias, with
// nothing to confirm. A full name is safe precisely because Outlook makes a
// human confirm it; a wrong alias is dangerous precisely because it does not.
export function resolveEmailRecipient(params: {
  username: string; // already just the local part — see resolveOutlookRecipient
  emailAdr: string;
  name: string;
  corporateDomains: string[];
}): ResolvedRecipient {
  const username = (params.username || '').trim();
  if (username) {
    const domain = params.corporateDomains[0] || '';
    return { to: domain ? `${username}@${domain}` : username, usedNameFallback: false };
  }
  const emailAdr = (params.emailAdr || '').trim();
  if (emailAdr && isCorporateEmailDomain(emailAdr, params.corporateDomains)) {
    return { to: emailAdr, usedNameFallback: false };
  }
  return { to: (params.name || '').trim(), usedNameFallback: true };
}

// Resolves an employee's manager mailbox for the CC line (§4.7). Optional —
// no row for this employee simply means no CC, never a warning or a hold.
export function findManagerEmail(
  employeeManagerMap: EmployeeManagerRule[],
  empId: string | undefined,
): string | undefined {
  const key = (empId || '').trim();
  if (!key) return undefined;
  const match = employeeManagerMap.find(r => r.empId.trim() === key);
  return match?.managerEmail.trim() || undefined;
}

// ---------------------------------------------------------------------------
// Section-based OPS mailbox pooling
// ---------------------------------------------------------------------------
//
// EMAIL_STAFF_CC_MANAGER cases are always drafted individually (one email per
// case) — they're already addressed to a specific person, nothing to pool.
// EMAIL_OPS cases route to a shared team mailbox instead, and multiple cases
// for the same Section on the same day are combined into ONE digest email
// (a compact table) rather than opening N separate drafts.
//
// A Section with no configured mailbox has its cases HELD, not redirected.
// This used to fall back to the individual Employee+CC Manager path, which
// quietly inverted the routing decision: §4.1 sends these cases to OPS
// precisely so the employee and their line manager are not the recipients, and
// sectionMailboxMap ships empty, so the default configuration turned every
// OPS-only case into a disciplinary notice addressed to the employee. Holding
// fails toward silence instead of toward disclosure; the held cases are
// reported by count and Section so the gap is fixed in config, not papered
// over at draft time.
//
// defaultOpsMailbox (config) is the catch-all for that gap: when set, an
// unmapped Section's cases are still pooled into their Section+date digest,
// but addressed to the default OPS mailbox (flagged ops_mailbox_is_default and
// noted in the body) instead of being held. It is still an OPS mailbox, so the
// routing decision above is preserved. Only when it is blank are cases held.

const OPS_DIGEST_TABLE_COLUMNS = ['Name', 'Emp ID', 'Date', 'Finding', 'Action', 'Var(min)', 'Notes'] as const;

// The "Actions fired (all, this row)" annotation is appended to a case's body
// unconditionally by reconciliationEngine.ts whenever a row fires more than
// one rule, regardless of which email template was selected — so matching
// this fixed phrase is reliable even though the surrounding template text is
// user-editable.
function extractMultiActionNote(body: string): string | null {
  const match = body.match(/Actions fired \(all, this row\): (.+)/);
  return match ? match[1].trim() : null;
}

// Renders the pooled cases as a plain-text table (Outlook drafts here are
// always .Body, not .HTMLBody, so this is best-effort column alignment, not
// real monospace). Per-case terminated/multi-finding flags — which would
// otherwise only exist as free text appended to each case's own body — are
// surfaced in the Notes column plus a trailing "Additional notes" block, so
// pooling never silently drops those audit signals.
export function renderOpsDigestTable(actions: EmailActionItem[]): string {
  const rows = actions.map(a => {
    const notes: string[] = [];
    if (a.is_terminated) notes.push('TERMINATED');
    if (extractMultiActionNote(a.body)) notes.push('multi-finding');
    return [
      a.name || '',
      a.emp_id || '',
      a.nominate_date || '',
      // Short label only. The raw `category` is a full rule trace that can run
      // past 120 characters, and every column here is padded to the widest
      // cell — one verbose row used to stretch the whole table far beyond a
      // readable width in a plain-text mail. The full trace is preserved
      // verbatim in the per-case detail block below the table.
      shortenFindingLabel(a.category || ''),
      a.taa_action || '',
      String(a.variance_minutes ?? ''),
      notes.length > 0 ? notes.join('; ') : '-',
    ];
  });

  const widths = OPS_DIGEST_TABLE_COLUMNS.map((header, i) =>
    Math.max(header.length, ...rows.map(r => r[i].length))
  );
  const formatRow = (cols: readonly string[]) => cols.map((c, i) => c.padEnd(widths[i])).join(' | ');
  const lines = [
    formatRow(OPS_DIGEST_TABLE_COLUMNS),
    widths.map(w => '-'.repeat(w)).join('-|-'),
    ...rows.map(formatRow),
  ];

  const extraNotes: string[] = [];
  actions.forEach(a => {
    // The full rule trace, kept out of the padded table but never dropped —
    // an OPS reviewer needs the measured minutes and the effective window to
    // check the verdict, and this digest is the only place they see it.
    const full = (a.category || '').trim();
    if (full && full !== shortenFindingLabel(full)) {
      extraNotes.push(`- ${a.name} (${a.emp_id}): ${full}`);
    }
    if (a.is_terminated) {
      extraNotes.push(`- ${a.name} (${a.emp_id}): AUDIT WARNING - this employee record is flagged TERMINATED - verify before acting on this notice.`);
    }
    const multiAction = extractMultiActionNote(a.body);
    if (multiAction) {
      extraNotes.push(`- ${a.name} (${a.emp_id}): Actions fired (all, this row): ${multiAction}`);
    }
  });

  const parts = [lines.join('\n')];
  if (extraNotes.length > 0) parts.push('', 'Case detail:', ...extraNotes);
  return parts.join('\n');
}

// Rewrites an EMAIL_OPS case to the individual Employee+CC Manager path.
//
// This is an OVERRIDE of the Communication Rule that actually fired, so it is
// never applied automatically any more — only the single-row "draft this one"
// icon uses it, and only after the operator has confirmed the override in a
// dialog that names the rule being overridden. Bulk drafting holds unmapped
// OPS cases instead (see poolEmailOpsActionsBySection).
//
// Safe to force once consented: communication_rule only selects whether a
// manager CC is looked up, it never affects which subject/body template was
// already baked into the item by applyEmailTemplate, and `to` was already
// resolved unconditionally at construction time regardless of which rule fired.
export function buildIndividualOverride(
  action: EmailActionItem,
  employeeManagerMap: EmployeeManagerRule[],
): EmailActionItem {
  return {
    ...action,
    communication_rule: 'EMAIL_STAFF_CC_MANAGER',
    cc: findManagerEmail(employeeManagerMap, action.emp_id),
  };
}

// Resolves a Section name to its configured mailbox using the same
// trim/upper-case keying the wizard's duplicate detection uses, so "Prestige",
// " prestige " and "PRESTIGE" are one Section everywhere.
export function buildSectionMailboxLookup(sectionMailboxMap: SectionMailboxRule[]): Map<string, string> {
  const mailboxBySection = new Map<string, string>();
  sectionMailboxMap.forEach(rule => {
    const key = rule.section.trim().toUpperCase();
    if (key && rule.mailbox.trim()) mailboxBySection.set(key, rule.mailbox.trim());
  });
  return mailboxBySection;
}

// Mapped Section mailbox first; otherwise the configured default OPS mailbox
// (when non-blank); otherwise undefined (the case is held).
export function findSectionMailbox(
  sectionMailboxMap: SectionMailboxRule[],
  section: string | undefined,
  defaultOpsMailbox?: string,
): string | undefined {
  return buildSectionMailboxLookup(sectionMailboxMap).get((section || '').trim().toUpperCase())
    || (defaultOpsMailbox || '').trim()
    || undefined;
}

export function poolEmailOpsActionsBySection(
  actions: EmailActionItem[],
  sectionMailboxMap: SectionMailboxRule[],
  emailTemplates: EmailTemplateRegistry,
  defaultOpsMailbox = '',
): { pooled: EmailActionItem[]; held: EmailActionItem[]; defaulted: EmailActionItem[] } {
  const mailboxBySection = buildSectionMailboxLookup(sectionMailboxMap);
  const fallbackMailbox = defaultOpsMailbox.trim();

  const groups = new Map<string, EmailActionItem[]>();
  actions
    .filter(a => a.communication_rule === 'EMAIL_OPS')
    .forEach(action => {
      const sectionKey = (action.section || '').trim().toUpperCase();
      const groupKey = `${sectionKey}||${action.nominate_date || ''}`;
      if (!groups.has(groupKey)) groups.set(groupKey, []);
      groups.get(groupKey)!.push(action);
    });

  const pooled: EmailActionItem[] = [];
  const held: EmailActionItem[] = [];
  const defaulted: EmailActionItem[] = [];

  groups.forEach((groupActions, groupKey) => {
    const [sectionKey, dateKey] = groupKey.split('||');
    const sectionMailbox = mailboxBySection.get(sectionKey);
    const mailbox = sectionMailbox || fallbackMailbox;
    const isDefault = !sectionMailbox && !!fallbackMailbox;
    if (!mailbox) {
      // Held unchanged — communication_rule stays EMAIL_OPS so nothing
      // downstream can mistake these for cases that were cleared to go to the
      // employee.
      groupActions.forEach(a => held.push(a));
      return;
    }

    const sectionLabel = groupActions[0].section || sectionKey;
    const caseTable = renderOpsDigestTable(groupActions);
    const digestBase: EmailActionItem = {
      row_id: `ops-digest-${sectionKey}-${dateKey}`,
      // A digest belongs to a Section+date group, not to one reconciliation
      // row, so it is its own base — nothing should ever map it back to a row.
      base_row_id: `ops-digest-${sectionKey}-${dateKey}`,
      template_key: 'ops_digest',
      emp_id: `SECTION:${sectionKey}`,
      name: sectionLabel,
      nominate_date: dateKey,
      role_tier: '',
      category: 'OPS Section Digest',
      variance_minutes: 0,
      taa_action: 'EMAIL_OPS_DIGEST',
      communication_rule: 'EMAIL_OPS',
      extra_2_alias: '',
      email_adr: '',
      resolved_username: '',
      login_id: '',
      section: sectionLabel,
      subject: '',
      body: '',
      to: '',
      ops_mailbox: mailbox,
      ...(isDefault ? { ops_mailbox_is_default: true } : {}),
    };
    const digest = applyEmailTemplate(digestBase, emailTemplates, {
      section: sectionLabel,
      count: String(groupActions.length),
      case_table: caseTable,
    });
    if (isDefault) {
      groupActions.forEach(a => defaulted.push(a));
      digest.body += `\n\nNote: Section "${sectionLabel || '(none)'}" has no OPS mailbox configured, so this digest was addressed to the default OPS mailbox. ` +
        'Add a Section mapping in the Email Config wizard to route it directly.';
    }
    pooled.push(digest);
  });

  return { pooled, held, defaulted };
}

// Single source of truth for turning raw per-row EmailActionItems into the
// final set of draft units: staff/manager cases stay individual, EMAIL_OPS
// cases pool by Section+date into digests, and EMAIL_OPS cases whose Section
// has no configured mailbox are HELD — excluded from finalActions rather than
// re-routed to the employee. Used by both the in-app Bulk Draft button and the
// downloadable Email Actions JSON so the two never diverge.
export function planEmailDraftActions(
  actions: EmailActionItem[],
  sectionMailboxMap: SectionMailboxRule[],
  emailTemplates: EmailTemplateRegistry,
  defaultOpsMailbox = '',
): {
  staffActions: EmailActionItem[];
  pooled: EmailActionItem[];
  held: EmailActionItem[];
  heldSections: string[];
  defaulted: EmailActionItem[];
  defaultedSections: string[];
  finalActions: EmailActionItem[];
} {
  const staffActions = actions.filter(a => a.communication_rule === 'EMAIL_STAFF_CC_MANAGER');
  const opsActions = actions.filter(a => a.communication_rule === 'EMAIL_OPS');
  const { pooled, held, defaulted } = poolEmailOpsActionsBySection(opsActions, sectionMailboxMap, emailTemplates, defaultOpsMailbox);
  const heldSections = Array.from(new Set(held.map(a => a.section || '(none)')));
  const defaultedSections = Array.from(new Set(defaulted.map(a => a.section || '(none)')));
  return {
    staffActions,
    pooled,
    held,
    heldSections,
    defaulted,
    defaultedSections,
    finalActions: [...staffActions, ...pooled],
  };
}

// ---------------------------------------------------------------------------
// Email outcome per reconciled row — the durable audit record
// ---------------------------------------------------------------------------
//
// Holding an unmapped EMAIL_OPS case is the correct routing decision, but on its
// own it converts a silent mis-delivery into a silent NON-delivery: the case is
// deliberately absent from the actions JSON, so the only trace was a banner that
// vanished with the browser tab. Nothing in any downloaded artifact recorded
// that a row required an email at all.
//
// This resolves every row to an outcome, and the annotated Cognos report
// (Output 2) carries it as TAA_EMAIL_STATUS alongside TAA_COMMUNICATION_RULE.
// It is derived from the SAME planEmailDraftActions result the Bulk Draft button
// and the downloadable JSON use, so the three can never disagree about what
// happened to a case.
export type EmailStatus =
  | 'NOT_REQUIRED'
  | 'DRAFTED_INDIVIDUAL'
  | 'DRAFTED_OPS_DIGEST'
  // Pooled into an OPS digest addressed to config.defaultOpsMailbox because the
  // case's Section has no mapping in sectionMailboxMap.
  | 'DRAFTED_OPS_DEFAULT_MAILBOX'
  | 'HELD_NO_OPS_MAILBOX'
  // Unseen-punch audit (src/services/unseenPunchAudit.ts) REASON flag: the ASPECT row stays in
  // output, but a punch outside the search window may change the reason shown to the employee
  // — only the email is held. See computeEmailStatusByRowId's unseenPunchHeldRowIds param.
  | 'HELD_UNSEEN_PUNCH'
  | 'EXCLUDED_FROM_OUTPUT';

// A row firing more than one action gets one EmailActionItem PER action
// (reconciliationEngine.ts), each carrying the reconciliation row it belongs to
// in base_row_id. Read that field — never split row_id on '#', which is unsafe
// because a PF NO can itself contain one (real occurrence: `PF NO = "PT #"` in
// samples_Files/Cognos.csv) and silently truncates the lookup key.
function baseRowId(action: EmailActionItem): string {
  return action.base_row_id;
}

export function computeEmailStatusByRowId(
  emailActions: EmailActionItem[],
  eligibleRowIds: ReadonlySet<string> | null,
  sectionMailboxMap: SectionMailboxRule[],
  emailTemplates: EmailTemplateRegistry,
  // Unseen-punch audit REASON flag (unseenPunchAudit.ts) — base_row_ids whose row stays in
  // output (still in eligibleRowIds) but whose EMAIL must be held anyway, since a punch outside
  // the search window may change the reason shown. Optional and additive: omitting it leaves
  // every existing caller's behaviour unchanged.
  unseenPunchHeldRowIds?: ReadonlySet<string>,
  defaultOpsMailbox = '',
): { statusByRowId: Map<string, EmailStatus>; statusByBaseRowId: Map<string, EmailStatus>; eligible: EmailActionItem[] } {
  const statusByRowId = new Map<string, EmailStatus>();

  // A row that fired an emailing rule but was excluded from the reviewed
  // outputs (unticked, or on a forced hold) still needs to say so — "no email
  // was drafted because the row itself was withheld" is a different fact from
  // "no email was required". eligibleRowIds holds plain reconciliation-row
  // ids, so this check must compare against the BASE id, not a per-action
  // composite one — otherwise every action past the first on a multi-action
  // row would be wrongly excluded even though the row itself is included.
  const eligible: EmailActionItem[] = [];
  emailActions.forEach(action => {
    if (eligibleRowIds && !eligibleRowIds.has(baseRowId(action))) {
      statusByRowId.set(action.row_id, 'EXCLUDED_FROM_OUTPUT');
    } else if (unseenPunchHeldRowIds && unseenPunchHeldRowIds.has(baseRowId(action))) {
      statusByRowId.set(action.row_id, 'HELD_UNSEEN_PUNCH');
    } else {
      eligible.push(action);
    }
  });

  const plan = planEmailDraftActions(eligible, sectionMailboxMap, emailTemplates, defaultOpsMailbox);
  plan.staffActions.forEach(a => statusByRowId.set(a.row_id, 'DRAFTED_INDIVIDUAL'));
  plan.held.forEach(a => statusByRowId.set(a.row_id, 'HELD_NO_OPS_MAILBOX'));
  plan.defaulted.forEach(a => statusByRowId.set(a.row_id, 'DRAFTED_OPS_DEFAULT_MAILBOX'));
  // Pooled digests are synthesized items with their own row_id, so the
  // contributing cases are credited from the pre-pool eligible set instead.
  eligible
    .filter(a => a.communication_rule === 'EMAIL_OPS' && !statusByRowId.has(a.row_id))
    .forEach(a => statusByRowId.set(a.row_id, 'DRAFTED_OPS_DIGEST'));

  // Aggregated down to ONE status per underlying row, for consumers that only
  // make sense at that grain (TAA_EMAIL_STATUS in the annotated report is one
  // column on one Cognos row, even when that row fired several actions).
  // Priority order: a still-stuck or excluded case outranks a different
  // action on the same row that already drafted fine — the most actionable
  // fact must never hide behind a successful sibling.
  // Walks the ACTIONS (not the status map's keys) so each status is attributed
  // via that action's own base_row_id — the map's keys are row_ids, which are
  // not safely parseable back to a row.
  const STATUS_PRIORITY: EmailStatus[] = ['EXCLUDED_FROM_OUTPUT', 'HELD_UNSEEN_PUNCH', 'HELD_NO_OPS_MAILBOX', 'DRAFTED_OPS_DEFAULT_MAILBOX', 'DRAFTED_OPS_DIGEST', 'DRAFTED_INDIVIDUAL', 'NOT_REQUIRED'];
  const statusByBaseRowId = new Map<string, EmailStatus>();
  emailActions.forEach(action => {
    const status = statusByRowId.get(action.row_id);
    if (!status) return;
    const base = baseRowId(action);
    const current = statusByBaseRowId.get(base);
    if (!current || STATUS_PRIORITY.indexOf(status) < STATUS_PRIORITY.indexOf(current)) {
      statusByBaseRowId.set(base, status);
    }
  });

  return { statusByRowId, statusByBaseRowId, eligible };
}

